
server:
  port: 8989
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 209715200
      max-request-size: 209715200 #200M


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: sclience.entity

#分页插件相关参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

